# -*- coding: utf-8 -*-
"""AI_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mPFcGNOwgTIS_DmEYoDMalmPZfyul8_T
"""

import cv2

!pip install face_recognition

import face_recognition

from google.colab import drive

drive.mount('/content/drive')

original_image = cv2.imread('/content/drive/MyDrive/AI python/Photo/group.jpg')

Amla_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Amla.png')
Amla_image_encoding = face_recognition.face_encodings(Amla_image)[0]

Buttler_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Buttler.png')
Buttler_image_encoding = face_recognition.face_encodings(Buttler_image)[0]

Villiers_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Villiers.png')
Villiers_image_encoding = face_recognition.face_encodings(Villiers_image)[0]

Dhoni_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Dhoni.jpg')
Dhoni_image_encoding = face_recognition.face_encodings(Dhoni_image)[0]

Finch_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Finch.png')
Finch_image_encoding = face_recognition.face_encodings(Finch_image)[0]

Gayle_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Gayle.png')
Gayle_image_encoding = face_recognition.face_encodings(Gayle_image)[0]

Gulbadin_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Gulbadin.png')
Gulbadin_image_encoding = face_recognition.face_encodings(Gulbadin_image)[0]

Guptil_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Guptill.png')
Guptil_image_encoding = face_recognition.face_encodings(Guptil_image)[0]

Hafeez_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Hafeez.png')
Hafeez_image_encoding = face_recognition.face_encodings(Hafeez_image)[0]

Holder_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Holder.png')
Holder_image_encoding = face_recognition.face_encodings(Holder_image)[0]

Karunaratne_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Karunaratne.png')
Karunaratne_image_encoding = face_recognition.face_encodings(Karunaratne_image)[0]

Kohli_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Kohli.png')
Kohli_image_encoding = face_recognition.face_encodings(Kohli_image)[0]

Malinga_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Malinga.png')
Malinga_image_encoding = face_recognition.face_encodings(Malinga_image)[0]

Mashrafe_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Mashrafe.png')
Mashrafe_image_encoding = face_recognition.face_encodings(Mashrafe_image)[0]

Morgan_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Morgan.png')
Morgan_image_encoding = face_recognition.face_encodings(Morgan_image)[0]

Plessis_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Plessis.png')
Plessis_image_encoding = face_recognition.face_encodings(Plessis_image)[0]

Rashid_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Rashid.png')
Rashid_image_encoding = face_recognition.face_encodings(Rashid_image)[0]

Rohit_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Rohit.png')
Rohit_image_encoding = face_recognition.face_encodings(Rohit_image)[0]

Sakib_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Sakib.jpg')
Sakib_image_encoding = face_recognition.face_encodings(Sakib_image)[0]

Sarfraz_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Sarfraz.png')
Sarfraz_image_encoding = face_recognition.face_encodings(Sarfraz_image)[0]

Smith_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Smith.png')
Smith_image_encoding = face_recognition.face_encodings(Smith_image)[0]

Stokes_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Stokes.png')
Stokes_image_encoding = face_recognition.face_encodings(Stokes_image)[0]

Tamim_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Tamim.png')
Tamim_image_encoding = face_recognition.face_encodings(Tamim_image)[0]

Taylor_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Taylor.png')
Taylor_image_encoding = face_recognition.face_encodings(Taylor_image)[0]

Warner_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Warner.png')
Warner_image_encoding = face_recognition.face_encodings(Warner_image)[0]

Williamson_image = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/Cricketers/Williamson.png')
Williamson_image_encoding = face_recognition.face_encodings(Williamson_image)[0]

known_face_encodings=[Amla_image_encoding, Buttler_image_encoding, Villiers_image_encoding, Dhoni_image_encoding, Finch_image_encoding, Gayle_image_encoding, Gulbadin_image_encoding, Guptil_image_encoding, Hafeez_image_encoding, Holder_image_encoding, Karunaratne_image_encoding, Kohli_image_encoding, Malinga_image_encoding, Mashrafe_image_encoding, Morgan_image_encoding, Plessis_image_encoding, Rashid_image_encoding, Rohit_image_encoding, Sakib_image_encoding, Sarfraz_image_encoding, Smith_image_encoding, Stokes_image_encoding, Tamim_image_encoding, Taylor_image_encoding, Warner_image_encoding, Williamson_image_encoding]
known_face_names=['Amla' , 'Buttler' , 'Villiers' , 'Dhoni' , 'Finch' , 'Gayle' , 'Gulbadin' , 'Guptil' , 'Hafeez' , 'Holder' , 'Karunaratne' , 'Kohli' , 'Malinga' , 'Mashrafe' , 'Morgan' , 'Plessis' , 'Rashid' , 'Rohit' , 'Sakib' , 'Sarfraz' , 'Smith' , 'Stokes' , 'Tamim' , 'Taylor' , 'Warner' , 'Williamson']

face_to_recognize = face_recognition.load_image_file('/content/drive/MyDrive/AI python/Photo/group.jpg')
face_locations = face_recognition.face_locations(face_to_recognize, model='hog')
face_encodings = face_recognition.face_encodings(face_to_recognize,face_locations)

from google.colab.patches import cv2_imshow

for current_face_location, current_face_encoding in zip(face_locations, face_encodings):
  top_pos, right_pos, bottom_pos, left_pos = current_face_location
  all_matches = face_recognition.compare_faces(known_face_encodings,current_face_encoding)
  name_of_person = 'Unrecognized'
  if True in all_matches:
    matched_index = all_matches.index(True)
    name_of_person = known_face_names[matched_index]
    cv2.rectangle(original_image,(left_pos,top_pos),(right_pos,bottom_pos),(255,0,0),2)
    font = cv2.FONT_HERSHEY_PLAIN
    cv2.putText(original_image,name_of_person,(left_pos,top_pos-10),font,0.6,(0,255,0))

cv2_imshow(original_image)